### ISSUE TITLE
似乎对时间的判断有问题？

### ISSUE THREAD

**Issue by justforlxz** [Lakr233/MoneyProgress#9]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/12298476/158917014-452c2ef3-32eb-4c52-bb25-a336930964cb.png">

<img width="378" alt="image" src="https://user-images.githubusercontent.com/12298476/158917033-77ee3a1a-0d57-4712-997c-f953c1c85b71.png">

设定的8点上班，已经快9点了，告诉我还没开工（

**Comment by Lakr233** [comment]
恢复默认试一下吧 我没处理边界条件 也不打算仔细修 毕竟图一乐 233

**Comment by Lakr233** [comment]
Fixed
